assets:
  - fredthrall.sql.gz
  - files.tgz
steps:
  - name: Load files
    plugin: Shell
    command: 'cd $SRC_DIR && tar -zxf $ASSET_DIR/files.tgz'
  - name: Probo.CI site setup
    plugin: Drupal
    database: fredthrall.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
